qcacmn: Fix -Wstrict-prototypes
drivers/staging/wlan-qc/qcacld-3.0/../qca-wifi-host-cmn/
hif/src/ce/ce_service_legacy.c:1320:34: error: a function
declaration without a prototype is deprecated in all versions
of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void
1 error generated.

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>